package alan;
import java.awt.Color;

public class Constants {

    // Display Constants
    public final static int REFRESH_RATE = 500;
    public final static int FRAME_WIDTH = 1200;
    public final static int FRAME_HEIGHT = 629;
    public final static Color SKY_BLUE = new Color(174,227,245);
    public final static Color BLACK = new Color(0,0,0);

    // Grid Constants
    public final static int CELL_WIDTH = 50;
    public final static int CELL_HEIGHT = 50;
    public final static int GRID_PANEL_WIDTH = (int)(FRAME_WIDTH/2);
    public final static int GRID_PANEL_HEIGHT = FRAME_HEIGHT;

    // Creature
    public static enum CREATURE_SIZE {TINY, SMALL, MEDIUM, LARGE, HUGE, GARGANTUAN, COLOSSAL};
    public static enum DAMAGE_TYPE {FIRE, ICE, LIGHTNING, POISON, ACID, SLASHING, PIERCING, BLUDGEONING, NECROTIC, RADIANT, FORCE, THUNDER, PSYCHIC};
    public static enum SKILL_KEY {ATHLETICS, ACROBATICS, SLEIGHT_OF_HAND, STEALTH, ARCANA, HISTORY, INVESTIGATION, NATURE,
        RELIGION, ANIMAL_HANDLING, INSIGHT, MEDICINE, PERCEPTION, SURVIVAL, DECEPTION, INTIMIDATION, PERFORMANCE, PERSUASION};
    public static enum CONDITION_KEY {BLINDED, CHARMED, DEAFENED, EXHAUSTION, FRIGHTENED, GRAPPLED, HEXED, HUNTERS_MARKED, INCAPACITATED, INVISIBLE,
        PARALYZED, PETRIFIED, POISONED, PRONE, RESTRAINED, STUNNED, UNCONSCIOUS, CHILL_TOUCH, AURA_AGATHYS, PROTECTION_GE, SANCTUARY, BURNING, FEATHER_FALL};
    public static enum ABILITY {STRENGTH, CONSTITUTION, DEXTERITY, INTELLIGENCE, WISDOM, CHARISMA};
    public static enum SCHOOL {EVOCATION, ABJURATION, NECROMANCY, ILLUSION, TRANSMUTATION, ENCHANTMENT, DIVINATION, CONJURATION,};
    public static enum CLASS {FIGHTER, RANGER, ROGUE, WIZARD, SORCERER, WARLOCK, DRUID, MONK, BARBARIAN, BARD, CLERIC, PALADIN};
    

    // Spells
    public static enum SPELL {ACID_SPLASH, BLADE_WARD, CHILL_TOUCH, DANCING_LIGHTS, DRUID_CRAFT, ELDRITCH_BLAST, ELEMENTALISM, FIRE_BOLT, FRIENDS, GUIDANCE, LIGHT, MAGE_HAND, MENDING, MESSAGE,
        MIND_SLIVER, MINOR_ILLUSION, POISON_SPRAY, PRESTIDIGITATION, PRODUCE_FLAME, RAY_OF_FROST, RESISTANCE, SACRED_FLAME, SHILLELAGH, SHOCKING_GRASP, SORCEROUS_BLAST, SPARE_THE_DYING,
        STARRY_WISP, THAUMATURGY, THORN_WHIP, THUNDERCLAP, TOLL_THE_DEAD, TRUE_STRIKE, VICIOUS_MOCKERY, WORD_OF_RADIANCE, ALARM, ANIMAL_FRIENDSHIP, ARMOR_OF_AGATHYS, ARMS_OF_HADAR, BANE, BLESS,
        BURNING_HANDS, CHARM_PERSON, CHROMATIC_ORB, COLOR_SPRAY, COMMAND, COMPELLED_DUEL, COMPREHEND_LANGUAGES, CREATE_OR_DESTROY_WATER, CURE_WOUNDS, DETECT_EVIL_AND_GOOD, DETECT_MAGIC,
        DETECT_POISON_AND_DISEASE, DISGUISE_SELF, DISSONANT_WHISPERS, DIVINE_FAVOR, ENSNARING_STRIKE, ENTANGLE, EXPEDITIOUS_RETREAT, FAERIE_FIRE, FALSE_LIFE, FEATHER_FALL, FIND_FAMILIAR, FOG_CLOUD,
        GOODBERRY, GREASE, GUIDING_BOLT, HAIL_OF_THORNS, HEALING_WORD, HELLISH_REBUKE, HEROISM, HEX, HUNTERS_MARK, ICE_KNIFE, IDENTIFY, INFLICT_WOUNDS, JUMP, LONGSTRIDER, MAGE_ARMOR, MAGIC_MISSILE,
        PROTECTION_FROM_EVIL_AND_GOOD, RAY_OF_SICKNESS, SANCTUARY, SEARING_SMITE, SHILED, SHILED_OF_FAITH, SLEEP, SPEAK_WITH_ANIMALS, TASHAS_HIDEOUS_LAUGHTER, THUNDEROUS_SMITE, THUNDERWAVE,
        WITCH_BOLT, WRATHFUL_SMITE, DIVINE_SMITE};

    // Classes and Features
    public static enum FEATURE {RAGE, UNARMORED_DEFENSE, WEAPON_MASTERY, BARDIC_INSPIRATION, WEAPON_FIGHTING_STYLE, ARCHERY, BLIND_FIGHTING, DEFENSE, DUELING, GREAT_WEAPON_FIGHTING, INTERCEPTION, PROTECTION, THROWN_WEAPON_FIGHTING, TWO_WEAPON_FIGHTING, UNARMED_FIGHTING};
    public static enum DIVINE_ORDERS {PROTECTOR, THAUMATURGE};
    public static enum PRIMAL_ORDERS {MAGICIAN, WARDEN};
    public static enum LANGUAGE {COMMON, DRUIDIC, UNDERCOMMON, ELVEN, DWARVISH, ABYSSAL, CELESTIAL, DEEP_SPEECH, INFERNAL, PRIMORDIAL, SYLVAN, THIEVES_CANT, DRACONIC, GIANT, GNOMISH, GOBLIN, HALFLING, ORC};
    public static enum FEAT_TYPE{ORIGIN, GENERAL, FIGHTING_STYLE, EPIC_BOON, CLASS};

    // Weapon and Armor
    public static enum WEAPON_PROFICIENCY {SIMPLE, MARTIAL};
    public static enum ARMOR_PROFICIENCY {LIGHT, MEDIUM, HEAVY, SHIELD};
    public static enum WEAPON_KEY {CLUB, DAGGER, GREATCLUB, HANDAXE, JAVELIN, LIGHT_HAMMER, MACE, QUARTERSTAFF, SICKLE, SPEAR, DART, LIGHT_CROSSBOW, SHORTBOW, SLING, BATTLEAXE, FLAIL, GLAIVE,
        GREATAXE, GREATSWORD, HALBRED, LANCE, LONGSWORD, MAUL, MORNINGSTAR, PIKE, RAPIER, SCIMITAR, SHORTSWORD, TRIDENT, WARHAMMER, WARP_PICK, WHIP, BLOWGUN, HAND_CROSSBOW, HEAVY_CROSSBOW, LONGBOW,
        MUSKET, PISTOL};
    public static enum MASTERY_SKILL{SLOW, NICK, PUSH, VEX, SAP, TOPPLE, GRAZE, CLEAVE};
}
